### ISSUE TITLE
Abnormal Ctrl+Z Behavior - Previous File Appears When Undoing in a New File

### ISSUE THREAD

**Issue by AdAstraAbyssoque** [tanpero/Vanella#3]
**Issue Description:**

I encountered an issue in the Vanella editor involving the undo (Ctrl+Z) function. Normally, if I edit file A.md, and then open and edit file B.md, the undo operation should only affect the currently open file, which is B.md. However, the current situation is that when I perform an undo operation in B.md, the system displays the contents of A.md, even though the editor still keeps B.md open.

**Steps to Reproduce:**

1. Open and edit file A.md in the Vanella editor.
2. Without closing file A.md, open and edit file B.md.
3. Perform an undo operation (Ctrl+Z) while editing B.md.

**Expected Behavior:**

The undo operation should only affect the currently open file, which is B.md.

**Actual Behavior:**

Although the editor still keeps B.md open, when performing an undo operation in B.md, the system displays the contents of A.md.

**Comment by tanpero** [comment]
That's an actual bug. I plan to address this issue after refactoring the editing method and manually establish a history stack for each file 😄
