### ISSUE TITLE
Line breaking issue when rendering LaTeX inline formulas in Markdown

### ISSUE THREAD

**Issue by AdAstraAbyssoque** [tanpero/Vanella#4]
**Issue Description:**

I have noticed that while using Markdown to render LaTeX inline formulas, the formulas are incorrectly rendered on a new line, instead of within the text line as expected. For instance, when I try to render the following text:

"For a discrete random variable $X$, the probability mass function $p$ is defined as:"

The formulas "$X$" and "$p$" are incorrectly rendered on a new line.

**Steps to Reproduce:**

1. Open the Markdown editor.
2. Input or paste the above text.
3. Preview or save the text, and observe the formula rendering.

**Expected Behaviour:**

I expect the inline formulas to be rendered within the line of text, not on a new line.

**Actual Behaviour:**

However, the formulas are incorrectly rendered on a new line.

**Comment by tanpero** [comment]
Thanks for  @AdAstraAbyssoque . It is [fixed](https://github.com/tanpero/Vanella/commit/5e9d651f5f7863e3dd63642a1d601a7d6ba25ee6) now.
